sudo: required

services:
  - docker

env:
  - ELASTICMQ_VERSION=0.7.1
  - ELASTICMQ_VERSION=0.8.12
  - ELASTICMQ_VERSION=0.9.3

before_install:
  - make load-docker-cache
  - make build

script:
  - make test

after_success:
  - make save-docker-cache
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    make publish;
    fi

cache:
  directories:
    - docker-cache
