FROM       java:7-alpine
MAINTAINER Yusuke KUOKA

ENV ELASTICMQ_VERSION %%ELASTICMQ_VERSION%%

ADD  https://s3-eu-west-1.amazonaws.com/softwaremill-public/elasticmq-server-${ELASTICMQ_VERSION}.jar /elasticmq/elasticmq-${ELASTICMQ_VERSION}.jar
ADD  run /elasticmq/run
RUN  chmod +x /elasticmq/run

EXPOSE 9324

ENTRYPOINT ["/elasticmq/run"]
CMD        []
